"""Generate a dummy ``doc/config.texi`` by parsing FFmpeg's ``configure`` script.

The real ``config.texi`` is produced by running ``./configure`` at build
time — it contains ``@set <name> yes`` lines for every feature the
configured build enabled, plus ``@c @set <name> yes`` (commented) for
disabled features.

For metadata extraction we don't want to run ``configure`` (it requires a
compiler, builds a probe, takes minutes, and produces host-specific
output). Instead we statically parse ``configure`` for the
``CONFIG_LIST``, ``CONFIG_EXTRA``, ``ARCH_LIST`` and ``HAVE_LIST`` shell
variables and emit ``@set`` for every option — pretending all features
are enabled.

This is enough for ``makeinfo`` to resolve ``@include config.texi`` and
to expand all ``@ifset config-…`` conditionals in the FFmpeg docs.
"""

from __future__ import annotations

import re

__all__ = ["generate_config_texi"]

# Lists in configure that map into config.texi, paired with their prefix.
_LISTS = [
    ("ARCH_LIST", "arch"),
    ("HAVE_LIST", "have"),
    ("CONFIG_LIST", "config"),
    ("CONFIG_EXTRA", "config"),
]

# Names that semantically mean "feature X is NOT active". Emitting these as
# ``@set`` would suppress content the docs render by default. None of these
# appear in the current FFmpeg configure lists, but the filter is cheap.
_SKIP_SUFFIXES = ("-not-all", "-readonly", "-writeonly")

# Names that must always appear, even if the configure parse doesn't see
# them. ``config-all`` historically came from --enable-all and isn't in any
# *_LIST; without it, the top-level @ifset gating ffmpeg.texi's includes
# evaluates false and the docs collapse to a small subset.
_ALWAYS_SET = ("config-all",)

# Match a shell variable assignment whose value is a double-quoted multi-line
# block, e.g. ``CONFIG_LIST="<newline>...<newline>"``.
_LIST_BLOCK_RE = re.compile(
    r'^([A-Z][A-Z0-9_]*)="\n(.*?)\n"\s*$',
    re.MULTILINE | re.DOTALL,
)

# A token inside a list body that references another variable: ``$NAME``.
_REF_RE = re.compile(r"\$([A-Z][A-Z0-9_]*)")


def _parse_lists(configure_text: str) -> dict[str, list[str]]:
    """Return ``{var_name: [tokens...]}`` for every ``NAME="..."`` block."""
    lists: dict[str, list[str]] = {}
    for match in _LIST_BLOCK_RE.finditer(configure_text):
        name, body = match.group(1), match.group(2)
        # Strip line comments before splitting.
        cleaned = re.sub(r"#.*", "", body)
        lists[name] = cleaned.split()
    return lists


def _resolve(name: str, lists: dict[str, list[str]], seen: set[str]) -> list[str]:
    """Flatten a list, recursively expanding ``$OTHERLIST`` references."""
    if name in seen:
        return []
    seen.add(name)
    out: list[str] = []
    for token in lists.get(name, []):
        ref = _REF_RE.fullmatch(token)
        if ref:
            out.extend(_resolve(ref.group(1), lists, seen))
        else:
            out.append(token)
    return out


def _texi_name(token: str) -> str:
    return token.strip().lower().replace("_", "-")


def generate_config_texi(configure_text: str, version: str | None = None) -> str:
    """Return the contents of a dummy ``config.texi`` for ``configure_text``.

    ``version`` (e.g. ``"8.1.1"``) is written as ``@set VERSION`` /
    ``@set FFMPEG_VERSION`` — the FFmpeg docs reference these in titles.
    """
    lists = _parse_lists(configure_text)

    lines: list[str] = [
        "@c auto-generated by ffmpeg-metadata-extractor (parses configure)",
    ]
    if version:
        lines.append(f"@set VERSION {version}")
        lines.append(f"@set FFMPEG_VERSION {version}")

    seen_names: set[str] = set()
    for list_name, prefix in _LISTS:
        for token in _resolve(list_name, lists, set()):
            name = _texi_name(token)
            if not name or not name.replace("-", "").replace(".", "").isalnum():
                continue
            full = f"{prefix}-{name}"
            if full in seen_names:
                continue
            if any(full.endswith(suffix) for suffix in _SKIP_SUFFIXES):
                continue
            seen_names.add(full)
            lines.append(f"@set {full} yes")

    for name in _ALWAYS_SET:
        if name not in seen_names:
            seen_names.add(name)
            lines.append(f"@set {name} yes")

    lines.append("")
    return "\n".join(lines)
